# Generated by Django 4.2.2 on 2024-12-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="is_paid",
            field=models.BooleanField(default=False, verbose_name="Платная публикация"),
        ),
    ]
